-- QUAL A QUANTIDADE DE ANIMAIS REGISTRADOS NO SISTEMA?

SELECT COUNT(*) AS ANIMAIS_REGISTRADOS
FROM animal;

-- QUAL O TOTAL DE VACINAS APLICADAS REGISTRADAS NO SISTEMA?

SELECT COUNT(VACINE_ID) AS VACINAS_APLICADAS
FROM ANIMAL;

-- QUANTOS ANIMAIS TEMOS REGISTRADOS PARA CADA CATEGORIA (BOVINO, SUINO, CAPRINO…)?

SELECT COUNT(ID_ANIMAL_FAMILY) AS CONTAGEM,
	ANIMAL_FAMILY.FAMILY AS FAMÍLIA
	FROM ANIMAL
	JOIN ANIMAL_FAMILY ON ANIMAL_FAMILY.ID = ANIMAL.ID_ANIMAL_FAMILY
	GROUP BY FAMÍLIA;
    
-- QUAL A CATEGORIA DE ANIMAIS QUE MAIS VACINAS RECEBEU?

SELECT COUNT(VACINE_ID) AS VACINAS_APLICADAS,
	ANIMAL_FAMILY.FAMILY AS FAMÍLIA
	FROM ANIMAL
	JOIN VACINE ON VACINE_ID = VACINE.ID
	LEFT JOIN ANIMAL_FAMILY ON ANIMAL.ID_ANIMAL_FAMILY = ANIMAL_FAMILY.ID
	GROUP BY FAMÍLIA
    ORDER BY VACINAS_APLICADAS DESC;