CREATE DATABASE NOTA_FISCAL_NORMALIZADA;

USE `NOTA_FISCAL_NORMALIZADA`;

CREATE TABLE `NOTA_FISCAL` (
	`NRO_NOTA` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NM_CLIENTE` VARCHAR(256) NOT NULL,
    `END_CLIENTE` VARCHAR(256) NOT NULL,
    `NM_VENDEDOR` VARCHAR(256) NOT NULL,
    `DT_EMISSAO` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `VL_TOTAL` FLOAT NOT NULL
    
);

CREATE TABLE `PRODUTO` (
	`COD_PRODUTO` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `DESC_PRODUTO` VARCHAR(256) NOT NULL,
    `UN_MED` CHAR (2) NOT NULL,
    `VL_PRODUTO` FLOAT NOT NULL
);

CREATE TABLE `ITEM_NOTA_FISCAL` (
	`NRO_NOTA` INT NOT NULL,
	`COD_PRODUTO` INT NOT NULL,
	`QTD_PRODUTO` INT NOT NULL,
	`VL_PRECO` INT NOT NULL,
    `VL_TOTAL` INT NOT NULL,
    PRIMARY KEY (NRO_NOTA, COD_PRODUTO),
    CONSTRAINT FK_NRO_NOTA_NOTA_FISCAL
			FOREIGN KEY (NRO_NOTA) REFERENCES NOTA_FISCAL (NRO_NOTA),
	CONSTRAINT FK_COD_PRODUTO_PRODUTO
			FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO)
);

INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO) VALUES ('Leite', 'LT', 4.50);
INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO) VALUES ('Desodorante', 'UN', 8.00);
INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO) VALUES ('Salame', 'KG', 40.00);

SELECT * FROM `PRODUTO`;

-- Nota Fiscal

INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL) VALUES ('Aragorn', 'Terra Média', 'Bilbo', 60.50);
INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL) VALUES ('Gandalf', 'Terra Média', 'Frodo', 89.00);
INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL) VALUES ('Boromir', 'Mordor', 'Sam', 120.00);
INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL) VALUES ('Galadriel', 'Valinor', 'Saruman', 140.00);

SELECT * FROM `NOTA_FISCAL`;

-- Itens da Nota


INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (1, 1, 2, 4.50, 9.00);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (1, 2, 3, 8.00, 24.00);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (1, 3, 1, 27.50, 27.50);

--

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (2, 1, 3, 4.50, 13.50);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (2, 2, 2, 8.00, 16.00);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (2, 3, 1, 59.50, 59.50);

--

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (3, 2, 4, 8.00, 32.00);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (3, 3, 2, 44.00, 88.00);

--

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (4, 1, 5, 4.50, 22.50);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (4, 2, 4, 8.00, 32.00);
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) VALUES (4, 3, 2, 42.50, 85.00);

SELECT * FROM `ITEM_NOTA_FISCAL`;



SELECT * FROM PRODUTO WHERE COD_PRODUTO = 3;

-- UPDATE, ATULIZANDO DADOS DE COLUNAS EM TABELAS
UPDATE PRODUTO 
SET VL_PRODUTO = 45, DESC_PRODUTO = 'Atualizado',
UN_MED = 'CX'
WHERE COD_PRODUTO = 3;

-- DELETE, EXCLUIDO REGISTROS DE TABELAS
DELETE FROM PRODUTO
WHERE COD_PRODUTO = 3;
-- NESTE CASO UMA EXCEÇÃP SERÁ LANÇADA
-- VIOLAÇÃO DA CONSTRAINT QUE AMARRA O PRODUTO AO ITEM DA NOTA FISCAL
-- NÃO É POSSÍVEL EXCLUIR UMA PKs QUE TEM DEPENDÊNCIAS EM FKs

INSERT INTO PRODUTO (DESC_PRODUTO, UN_MED, VL_PRODUTO) VALUES ('Teste delete', 'LT', 5.50);

SELECT * FROM PRODUTO;

DELETE FROM PRODUTO WHERE COD_PRODUTO = 4;
