USE `nota_fiscal_normalizada`;

DELIMITER $$

CREATE TRIGGER PROMO_CHECK
BEFORE UPDATE ON produto
FOR EACH ROW
BEGIN

	DECLARE NOME VARCHAR(256);
    /* ELE CRIA A VARIAVEL NOME */
    
    SELECT DESC_PRODUTO
    /* SELECIONA A DESCRICAO DO PRODUTO */
    INTO NOME
    /* GUARDA NA VARIAVEL NOME */
    FROM PRODUTO
    WHERE COD_PRODUTO = NEW.COD_PRODUTO;
    
    IF NEW.VL_PRODUTO < 100 THEN
		SET NEW.DESC_PRODUTO =
			CONCAT('PROMOÇÃO', ' ', NOME);
		ELSEIF NEW.VL_PRODUTO >= 100 AND
			NEW.VL_PRODUTO <= 200 THEN
		SET NEW.DESC_PRODUTO = 
			CONCAT('OFERTA', ' ', NOME);
	END IF;
END $$

DELIMITER ;

/* Desativar trigger */
DROP TRIGGER PROMO_CHECK;